-- ============================================================================
-- NexGen Knowledge Base Seed Data
-- Generated from all 10 Compass pages
-- Target: knowledge_base table in Supabase
-- ============================================================================
-- This file populates the AI chatbot's brain with structured knowledge about
-- every role, every procedure, every metric, every meeting, and every
-- escalation path at NexGen School for Early Life Foundations.
-- ============================================================================

-- ─── BUSINESS CONTEXT: WHO ARE WE ──────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'identity', 'NexGen — Who We Are',
 'NexGen School for Early Life Foundations is an early childhood education center in Harlingen, TX committed to providing exceptional care, safety, and learning for every child served. NexGen is not just a daycare — it is the first chapter of a child''s story. Every classroom, every routine, every interaction is intentionally designed to build confidence, curiosity, and character from day one. NexGen serves children from 6 weeks through school age with full-day care, afterschool programming, and self-defense training built into the curriculum. NexGen holds Texas Rising Star (TRS) certification, reflecting a commitment to going beyond the minimum. The school audits itself constantly, trains relentlessly, and documents everything.',
 '{identity, mission, organization, about, nexgen}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 1, 1);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'mission', 'NexGen — Mission Statement',
 'NexGen''s mission is to build the foundation that every child deserves — through safe environments, exceptional educators, and systems that never cut corners. NexGen exists to give children the strongest possible start in life, holding itself to a higher standard than what is required because the families who trust the school are counting on it. Every child deserves the same quality start regardless of their zip code or family income. NexGen exists to close the gap between affordable and excellent.',
 '{mission, purpose, values, why}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 1, 2);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'values', 'NexGen — Core Values',
 'NexGen operates by six core values that serve as the filter for every decision: (1) Safety Above All — every child goes home safe, no exceptions, no excuses, safety is never negotiated. (2) Excellence, Always — good enough is not the standard, NexGen pursues operational and educational excellence relentlessly in every room every day. (3) Innovation — the team builds systems that scale, adopts better tools, and never gets comfortable with the old way if a better way exists. (4) Family Partnership — parents are not customers, they are partners, the school communicates openly, acts with integrity, and treats every family like its own. (5) Accountability — the team owns its outcomes, if something is not working it gets fixed, no finger-pointing, only solutions. (6) Grow Every Day — NexGen invests in team growth because the children deserve educators who never stop improving.',
 '{values, culture, principles, standards}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 1, 3);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'leadership', 'NexGen — Leadership Team',
 'NexGen operates on the Visionary/Integrator model. Roman is the Founder and CEO, serving as the Visionary — he sets the direction for NexGen, defines the vision, builds the strategy, identifies growth opportunities, and focuses on brand, culture, partnerships, and the long-term picture. Robyn is the Director of Operations, serving as the Integrator — she runs the day-to-day, translating the vision into execution, managing staff, ensuring classroom quality, upholding compliance, and making sure NexGen delivers on its promises to every family every single day. If Roman sets the destination, Robyn builds the road to get there.',
 '{leadership, team, roman, robyn, visionary, integrator}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 2, 4);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'differentiators', 'NexGen — What Makes Us Different',
 'NexGen differentiates itself in six key ways: (1) TRS Certified — independently verified to meet Texas Rising Star quality standards. (2) Self-defense curriculum — children are given tools to protect themselves, building confidence early. (3) Document everything — systems are built to be consistent, auditable, and improvable. (4) Staff treated as assets — the school invests in the team, not just the program. (5) Family partnership — parents are informed, involved, and treated as teammates. (6) Never stop improving — the school audits, iterates, and elevates constantly.',
 '{differentiators, competitive, advantage, trs, self-defense}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 2, 5);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'programs', 'NexGen — Programs and Enrollment Tiers',
 'NexGen provides safe, structured, high-quality early childhood education and care. The school serves working families in Harlingen, TX who want more than just a place to drop their child off. Programs are built around safety, learning, and family partnership. NexGen offers six programs: (1) Infant and Toddler Care for ages 6 weeks to 3 years with responsive, nurturing, developmentally appropriate classrooms, (2) Pre-K and Kinder Programs with school-readiness curriculum aligned to TRS standards, (3) Afterschool Program with structured homework support and enrichment activities, (4) Self-Defense Curriculum with age-appropriate confidence and safety training, (5) Family Communication with daily updates and open-door policy, (6) TRS-Certified Environment independently verified to meet quality standards. Enrollment tiers by age: Infant Care (6 weeks to 12 months), Older Infant (12 to 18 months), Young Toddler (18 to 24 months), Toddler (2 to 3 years), Pre-Kinder (3 to 4 years), Kinder (4 to 5 years), Afterschool Program (5+ years). All rates are weekly — contact Front Desk for current pricing and availability.',
 '{programs, enrollment, tiers, ages, pricing, services}', 'who-are-we', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 2, 6);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'school_metrics', 'NexGen — School-Wide KPIs',
 'NexGen tracks five school-wide metrics: (1) Enrollment Capacity — target 85%+, green at 85-100%, yellow at 70-84%, red below 70%. (2) TRS Star Rating — target 4-Star, green at 4-5 Star, yellow at 3 Star, red at 2 Star or below. (3) Family Retention Rate — target 85%+, green at 85%+, yellow at 70-84%, red below 70%. (4) Staff Turnover (Annual) — target under 20%, green under 20%, yellow 20-35%, red above 35%. (5) Incident Reports (Monthly) — target 0 critical, green at 0 critical, yellow at 1-2 minor, red at any critical or pattern of minor incidents.',
 '{metrics, kpis, school-wide, enrollment, trs, retention, turnover, incidents}', 'important-metrics', '{founder, operator, director}', 2, 7);

-- ─── FOUNDER — ALL PAGES ────────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — What Do I Do',
 'The Founder sets the vision and owns the financial health of NexGen. The Founder does not run daily operations — that is the Operator and Director. The Founder''s job is to build systems, monitor the numbers, make strategic decisions, and ensure the business can scale. With 14 team members and a daycare, treating separate departments as distinct entities creates unnecessary complexity. The real constraint is filling seats profitably — everything else is noise. The business collapses to 3 core functions with clear ownership and tracks only 10-12 numbers. The 3 core functions are: (1) Enrollment (Marketing + Sales) — owned by Robyn + Robyne + Ed, target of 20 new students and 100 customer reviews, covering ads, inquiries, tours, enrollments, and reviews with KPIs including new leads/week, tours held/week, new enrollments/week, and occupancy %. (2) Experience and Retention (Fulfillment + CS + HR) — owned by Rachel (Director) + Robyn, covering classroom quality, TRS, parent happiness, and kid retention with KPIs including % classrooms green on TRS, staff attendance, family churn %, and parent complaints. (3) Cash and Admin (Targets + Tech) — owned by the Founder + bookkeeper/admin, covering billing, collections, payroll, and basic HR paperwork with KPIs including total revenue and net profit, avg revenue/child, payroll % of revenue, and on-time collection rate. Core responsibilities: own the financial health of NexGen (revenue, expenses, profit margin), set the vision, quarterly goals, and growth strategy, run the 3-function model, review 10-12 KPIs weekly and monthly, conduct Monthly Finance Review with Robyn (60-90 min), lead Weekly Leadership Memos with Robyn and Rachel (45-60 min), request 3 reports monthly from bookkeeper by the 15th (P&L, Balance Sheet, Aged Receivables), make one specific finance decision every monthly review, and build and improve the systems that let the business run without the Founder in the room. The standard: You don''t just monitor it — you monitor and decide. Your job is to stare at a few key numbers and have the courage to pull the obvious lever: raise price, fill more seats, or cut dumb costs.',
 '{founder, responsibilities, vision, finance, functions, enrollment, retention, cash}', 'what-do-i-do', '{founder}', 1, 10);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — How Do I Do It',
 'The Founder''s procedures and operating rhythm: (1) Monthly Bookkeeper Request (by the 15th) — request 3 reports: P&L by month, Balance Sheet (cash position and debt), and Aged Receivables (subsidy vs. private pay breakdown). Group expenses into 5 buckets: Payroll, Facility, Food & Classroom, Admin/Software/Insurance, Other. (2) Monthly Owner Finance Routine (60 min with Robyn, optionally bookkeeper on Zoom) — Step A: Review last 3 months P&L for revenue trend. Step B: Check 3 key ratios. Step C: Ask 3 diagnostic questions. Step D: Pick ONE finance decision. (3) 3 Key Financial Ratios — Payroll % of Revenue (target 50-55%), Average Revenue per Child (are you charging enough?), Net Profit % (target 20%+). (4) 3 Diagnostic Questions — Do we need to fill more seats? Do we need to raise prices? Do we need to control a cost bucket? (5) Pick ONE Finance Decision every monthly meeting — raise rates, cut/renegotiate expenses, or push enrollment. No meeting ends without a decision. (6) Weekly Scoreboard — 4 numbers with Robyn: Occupancy %, New Enrollments/Withdrawals, Total Payroll Dollars, Cash in Bank. (7) Daily Huddle (10-15 min) with Robyn + Rachel + Andrea — staffing/ratios, tours, fires. Goal: Does today break anywhere? (8) Weekly Leadership Memos (45-60 min) with Robyn + Rachel — Scorecard Review, Wins/Losses, Top 3 Priorities, Who/What/When. (9) 3 Core Functions Oversight — Enrollment (Robyn + Andrea), Experience & Retention (Rachel + Robyn), Cash & Admin (Founder + bookkeeper). (10) Quarterly Planning — set and cascade goals across all 3 functions. Tool Stack: Slack is the central hub. NexGen Operating System is the focal point. Functions: Acquisition (Bitsync, Facebook, Google Ads), Delivery (Bitsync), Marketing & Content (Canva, SurveyMonkey), Operations (Google Workspace, Gusto), Management (Google Workspace, Gusto, Bitsync, SurveyMonkey, ClickUp).',
 '{founder, procedures, finance, bookkeeper, ratios, scoreboard, huddle, tools}', 'how-do-i-do-it', '{founder}', 4, 11);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — How Do I Know (Performance Scoring)',
 'The Founder is measured by the financial health and strategic clarity of the entire operation. Performance categories and weights: (1) Financial Health (35%) — Are you monitoring the right numbers and making decisions from them? Indicators: Monthly P&L reviewed with Robyn (green: every month by the 20th, red: skipped or inconsistent), Net profit margin tracking (green: 20%+ consistently, red: below 10% or unknown), Payroll % of revenue (green: 50-55%, red: above 65%), One specific finance decision made per monthly review (green: every month, red: rarely or never). (2) Enrollment & Growth (30%) — Is the enrollment function producing results? Indicators: Occupancy rate (green: 85%+, red: below 70%), Weekly enrollment KPIs reviewed (green: every week with Robyn, red: inconsistent), Tour-to-enrollment conversion trend (green: improving or stable, red: declining). (3) Experience & Retention (20%) — Is the Director keeping classrooms excellent and families happy? Indicators: TRS compliance maintained (green: 4+ Star, red: below 3 Star), Family churn % (green: below 5%/month, red: above 10%), Parent complaints resolved (green: all within 24 hrs, red: unresolved or patterns). (4) Systems & Cadence (15%) — Are weekly and monthly rhythms happening? Indicators: Daily Huddle happening (green: every day, red: sporadic), Weekly Leadership Memos held (green: every Tuesday, red: inconsistent), Monthly Finance Review completed (green: every month, red: skipped).',
 '{founder, performance, scoring, financial, enrollment, retention, systems}', 'how-do-i-know', '{founder}', 6, 12);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — Important Metrics',
 'The Founder tracks the health of the whole machine across 3 core functions. North star question: Are we filling seats profitably and is every function owner hitting their 3-4 numbers? Cadence: Weekly scoreboard with Robyn, monthly finance review, quarterly deep dive. Big Targets: 20 New Students (shared — Robyn + Robyne + Ed), 100 Customer Reviews (Google/Facebook — social proof for enrollment growth). Metrics by category: (1) Enrollment KPIs (Robyn, weekly): New Leads/Week, Tours Held/Week, New Enrollments/Week, Occupancy % (enrolled divided by 175, green 85%+). (2) Experience & Retention KPIs (Rachel, weekly/monthly): % Classrooms Green on TRS Checklist (target 100%), Staff Attendance/Call-Outs (target 95%+), Family Churn % (target below 5% monthly), Parent Complaints/Serious Issues (target zero critical). (3) Cash & Admin KPIs (Founder, monthly): Total Revenue & Net Profit (monthly P&L review), Average Revenue per Child, Payroll % of Revenue (target 50-55%), On-Time Collection Rate (target 95%+). (4) Weekly Scoreboard: Occupancy %, New Enrollments/Withdrawals (target net positive), Total Payroll Dollars (target in budget), Cash in Bank (target above 1 month expenses).',
 '{founder, metrics, kpis, enrollment, retention, cash, scoreboard, targets}', 'important-metrics', '{founder}', 6, 13);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — When Do I Do It (Schedule)',
 'The Founder''s rhythm is Daily + Weekly + Monthly. The standard: Weekly is about staying out of trouble. Monthly is about making more money. Daily: Morning Daily Huddle (10-15 min) with Robyn + Rachel + Andrea covering staffing/ratios, tours scheduled, any fires. Weekly: Monday — Weekly Scoreboard with Robyn (4 numbers: Occupancy %, New Enrollments/Withdrawals, Total Payroll Dollars, Cash in Bank). Tuesday — Weekly Leadership Memos (45-60 min) with Robyn + Rachel covering Scorecard Review, Wins/Losses, Top 3 Priorities, Who/What/When. Wednesday — Deep work: systems building, strategy, content, growth planning. Thursday — Follow up on action items, review operational flags. Friday — Weekly close, what got done, what moves to next week. Monthly: Monthly Finance Review (60-90 min) with Robyn reviewing P&L, 3 key ratios, 3 diagnostic questions, ONE finance decision. Bookkeeper reports due by the 15th. Review all 10-12 KPIs across 3 functions. Progress check on quarterly goals. Full staff meeting close with vision and direction.',
 '{founder, schedule, daily, weekly, monthly, rhythm, huddle, scoreboard}', 'when-do-i-do-it', '{founder}', 3, 14);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — What Do We Talk About (Communication)',
 'The Founder talks about numbers, strategy, and what needs to change at the system level. Communication channels: (1) Founder to Operator + Director (down): Weekly Scoreboard with 4 key numbers every Monday with Robyn, KPI review and accountability during Weekly Leadership Memos, finance decisions and pricing strategy during Monthly Finance Review (one decision per meeting, no exceptions), quarterly goals and strategic direction, vision and culture during full staff meetings. (2) Founder to External (community/partners): NexGen''s vision and positioning at community events, growth plans and expansion for second location readiness, strategic partnerships with technology and community organizations. Never: Bypass the Operator or Director to manage individual staff, handle billing/collections/payroll directly, get pulled into daily fires the Operator should solve, skip the monthly finance review. Systems: Slack is the central communication platform — if it is not in Slack it did not happen. NexGen Operating System is the single source of truth for role clarity, procedures, KPIs, escalation paths, and meeting cadences.',
 '{founder, communication, channels, strategy, external, slack}', 'what-do-we-talk-about', '{founder}', 5, 15);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — Where Do We Go (Escalation Guide)',
 'The Founder''s escalation guide. Golden rule: If you are solving a problem that should be solved by the Operator or Director, that is a systems gap — fix the system, not the symptom. Most answers live in the Founder''s data or a conversation with the Operator. Financial & Strategy: Revenue trending down — pull the Monthly Finance Review forward, ask the 3 diagnostic questions, pick ONE decision (same day, contact Operator). Raise prices? — Monthly Finance Review question, check Avg Revenue per Child and Net Profit %, pricing changes are the highest-ROI lever (routine). Payroll too high — target 50-55%, review staffing vs. enrollment ratios with Director (same day). Second location — not needed until multiple locations or $3M+ revenue with complex debt/grants (routine). Enrollment & Growth: Occupancy below target — check weekly enrollment KPIs with Robyn for leads, tours, conversions to identify broken lever (same day). Marketing not generating leads — review Marketing function with Robyn (routine). People & Operations: Operator not performing — address in weekly memos, document patterns (routine). Director declining — Operator should manage this (routine). Critical compliance issue — Operator and Director handle together, Founder stays informed (immediate).',
 '{founder, escalation, problems, decisions, financial, enrollment, compliance}', 'where-do-we-go', '{founder}', 5, 16);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'founder', 'Founder — Why Is It Important',
 'The Founder''s role matters because if the business is not healthy, nothing else survives. Every classroom, every teacher, every meal served, every child who walks through the doors depends on the financial health and strategic clarity of the business. Without revenue, there is no payroll. Without systems, there is no consistency. Without someone watching the numbers and having the courage to make hard decisions, the whole operation drifts. The Founder is not running the daily operation — that is the Operator and Director — but the Founder is running the machine that makes the daily operation possible. The families who trust NexGen are trusting that someone at the top is building something that will last. Pricing changes are usually the highest-ROI lever by far. Key stats: The Founder oversees 3 core functions, tracks 10-12 KPIs across the entire operation, and makes a minimum of 1 finance decision per monthly review.',
 '{founder, importance, motivation, purpose, financial, leadership}', 'why-is-it-important', '{founder}', 8, 17);

-- ─── OPERATOR — ALL PAGES ───────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — What Do I Do',
 'The Operator is responsible for the overall health of the business — financially, operationally, and strategically. The Operator''s job is to make sure all departments are functioning, all systems are built, and all leaders have what they need to succeed. The Operator does not manage classrooms — the Operator manages the people who manage classrooms. The Operator has two focus areas: (1) Delivery Focus (Retention) — Customer Satisfaction (parents'' experience), Product (4-star TRS Rating and beyond), Service (response rate, tonality, quality of response), Fulfillment (ease and speed of everything families interact with). (2) Revenue Focus (Enrollment) — Sales (speed and sequencing of lead follow-up and enrollment conversions), Marketing (structure, thinking, data, and AI driving visibility and lead generation), Tours (conversion rates, tour quality, follow-up execution). Responsibilities: Set the vision, goals, and quarterly priorities. Oversee all department leads and hold them accountable to their KPIs. Manage business finances, enrollment targets, and growth strategy. Build and maintain systems. Make hiring decisions for leadership roles. Represent NexGen externally. Identify problems before they become crises. Ensure the Director has everything needed. The standard: Work ON the business, not IN it. If you are solving problems someone else should own, that is a systems gap to fix.',
 '{operator, responsibilities, delivery, revenue, strategy, management}', 'what-do-i-do', '{operator}', 1, 20);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — How Do I Do It',
 'The Operator''s procedures: (1) Morning Check-In Routine — review priorities, check tours, set the building up for success. (2) Delivery Focus: Customer Satisfaction — evaluate and improve parents'' experience through feedback loops, NPS, and proactive outreach. (3) Delivery Focus: Product & TRS Quality — monitor and drive toward a 4-star TRS Rating with observations, scoring, and improvement plans. (4) Delivery Focus: Service & Fulfillment — measure response rate, tonality, quality of response, and ease and speed families experience. (5) Revenue Focus: Sales Pipeline — manage speed and sequencing of enrollment lead follow-up, conversion tracking, and closing. (6) Revenue Focus: Marketing & AI — build structure, thinking, data, and AI into the marketing engine. (7) Revenue Focus: Tour Conversions — track and improve tour-to-enrollment conversion rates. (8) Quarterly Planning Process — set and cascade quarterly goals across all departments. (9) Financial Review & Budget Management — review P&L, manage cash flow, approve expenditures. (10) Systems Audit Checklist — monthly audit of all operational systems to identify gaps.',
 '{operator, procedures, delivery, revenue, financial, systems, marketing}', 'how-do-i-do-it', '{operator}', 4, 21);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — Important Metrics',
 'The Operator measures the health of the whole business. North star: Is NexGen growing, financially healthy, and operationally excellent simultaneously? Cadence: Weekly financial review, monthly business review, quarterly deep dive. Financial metrics: Monthly Revenue vs. Target (green: at or above), Operating Expense Ratio (green: under 75% of revenue), Net Profit Margin (green: 15%+). Enrollment metrics: Current Enrollment vs. Capacity (green: 85-100%), Month-over-Month Growth (green: growing or stable), Waitlist Length (green: 5+ on waitlist). Operations metrics: TRS Compliance Status (green: 4-5 Star maintained), Staff Turnover Rate (green: under 20% annually), Outstanding Compliance Items (green: none).',
 '{operator, metrics, kpis, financial, enrollment, operations, trs}', 'important-metrics', '{operator}', 6, 22);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — When Do I Do It (Schedule)',
 'The Operator''s rhythm is Daily + Weekly + Monthly. The standard: Your job is not to run the daily operation — it is to make sure the daily operation runs itself. Daily: Arrival — check in, review priorities. First 30 min — view tours, ensure Tour Manager is prepped. Morning Block — Delivery Focus with four lenses: Customer Satisfaction, Product (TRS), Service (response quality), Fulfillment (ease and speed). Midday Block — Revenue Focus with three levers: Sales (lead follow-up), Marketing (AI and data-driven), Tours (conversions). Weekly: Monday — review KPIs and enrollment numbers, set priorities. Tuesday — all meetings stacked (Director check-in, department leads, external calls). Wednesday — deep work (strategy, systems, content). Thursday — follow up on action items, review flags. Friday — weekly close and financial snapshot. Monthly: Full financial review, Director performance review, quarterly goals progress, hiring pipeline review, identify one system to build/improve/eliminate.',
 '{operator, schedule, daily, weekly, monthly, rhythm, delivery, revenue}', 'when-do-i-do-it', '{operator}', 3, 23);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — What Do We Talk About',
 'The Operator talks about direction, performance, and what needs to change. Communication to Director (down): Weekly priorities and focus areas every Tuesday, performance expectations and standards, strategic decisions affecting operations, financial targets and enrollment goals monthly, culture and values reinforcement, recognition and accountability. Communication to External (community/partners): NexGen''s vision and positioning, TRS certification and quality standards, growth plans and expansion, strategic partnerships. Never: Bypass the Director to manage individual staff, discuss financial details or salary with anyone other than the Director, make promises to families without Director alignment, air internal conflicts outside leadership.',
 '{operator, communication, channels, director, external, strategy}', 'what-do-we-talk-about', '{operator}', 5, 24);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — Where Do We Go (Escalation Guide)',
 'The Operator''s escalation guide. Golden rule: If it is happening in the building, the Director should know before you do. If she does not, that is the first question to ask. Business & Financial: On track for enrollment targets? — pull from weekly KPI review (routine, contact Director). Financial shortfall this month — address together, Director owns operational context, Operator owns financial response (same day). Second location — quarterly review conversation (routine). Compliance & Licensing: Licensing notice or complaint — address together with Director, loop in DFPS if required (immediate). TRS assessment readiness — Director should be running ongoing prep (same day). Staff & People: Staff termination needed — Director and Operator align before action, document everything (same day). Director performance declining — address in weekly check-in, don''t let it accumulate (routine).',
 '{operator, escalation, problems, compliance, licensing, staff}', 'where-do-we-go', '{operator}', 5, 25);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'operator', 'Operator — Why Is It Important',
 'The Operator''s role matters because without strong leadership, nothing else holds. Every system, every standard, every staff member''s ability to show up and do their job well traces back to the decisions made at the top. When the Operator is clear, the Director is confident. When the Director is confident, teachers are focused. When teachers are focused, children thrive. It flows in one direction. The Operator''s decisions, standards, and attention to business health have a direct impact on every child served even without stepping into a classroom. If the business is not healthy, the classrooms are not safe. Key stats: Every enrolled child depends on the school''s stability, every employee depends on leadership clarity, and every family trusts the Operator''s systems.',
 '{operator, importance, motivation, purpose, leadership}', 'why-is-it-important', '{operator}', 8, 26);

-- ─── DIRECTOR — ALL PAGES ───────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — What Do I Do',
 'The Director translates the Operator''s vision into daily reality. The Director is the highest on-site authority, responsible for staff performance, compliance, parent satisfaction, and operational excellence. When something goes wrong on the floor, it starts and ends with the Director. Responsibilities: Supervise all teachers, assistants, and support staff daily. Conduct regular classroom observations and provide immediate feedback. Manage TRS compliance, licensing requirements, and state documentation. Handle parent escalations and build strong family relationships. Lead weekly team check-ins and staff development meetings. Approve lesson plans and ensure curriculum standards are met. Monitor enrollment, ratios, and daily attendance. Identify staffing gaps and communicate hiring needs to the Operator. Enforce NexGen''s culture, standards, and non-negotiables every day. The standard: You are the culture carrier. What you tolerate becomes the standard. What you celebrate becomes the culture.',
 '{director, responsibilities, compliance, trs, staff, families, culture}', 'what-do-i-do', '{director}', 1, 30);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — How Do I Do It',
 'The Director''s procedures: (1) Daily Walkthrough Checklist — morning, midday, and end-of-day classroom observation routine. (2) Staff Feedback & Coaching — real-time feedback and monthly performance conversations. (3) TRS Compliance Documentation — step-by-step guide to maintaining all TRS-required records. (4) Parent Escalation Protocol — handling complaints, concerns, and difficult family conversations. (5) Weekly Team Meeting Structure — agenda template, preparation, and follow-up process. (6) Ratio & Attendance Monitoring — daily process for tracking ratios and flagging coverage gaps.',
 '{director, procedures, walkthrough, coaching, trs, parents, meetings, ratios}', 'how-do-i-do-it', '{director}', 4, 31);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — How Do I Know (Performance Scoring)',
 'The Director is measured by the health of the building. Performance categories: (1) TRS Compliance (25%) — all staff credentials current (green: 100%), classroom environments meet criteria (green: all pass), documentation complete and accessible (green: fully documented). (2) Internal Observations (25%) — classrooms observed weekly (green: all rooms every week), feedback given after observations (green: same day), improvement tracked over time (green: clear upward trend). (3) Staff Performance & Retention (20%) — staff turnover rate (green: below 20% annually), outstanding performance issues (green: none unaddressed), training completion rate (green: 100%). (4) Parent Satisfaction (20%) — formal parent reviews (green: 4.5+ avg), complaint resolution time (green: within 24 hrs), family retention rate (green: above 85%). (5) Operational Consistency (10%) — daily schedule followed (green: consistent), incident reports completed same day (green: 100%).',
 '{director, performance, scoring, trs, observations, staff, families, operations}', 'how-do-i-know', '{director}', 6, 32);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — Important Metrics',
 'The Director measures the health of the building. North star: Is every classroom safe, every family retained, and every staff member accountable? Cadence: Daily awareness, weekly report to Operator, monthly full review. Compliance & Quality: TRS Classroom Compliance Rate (target 100%), Staff Training Hours Current (target 100%), Incident Reports Filed Same Day (target 100%). People: Open Performance Issues Unresolved (target zero), Staff Attendance Rate (target 95%+), Teacher Observation Completed Weekly (target all classrooms). Families: Parent Satisfaction Score (target 4.5+ out of 5), Complaint Resolution Time (target within 24 hours), Family Retention Rate (target 85%+).',
 '{director, metrics, kpis, compliance, people, families, retention}', 'important-metrics', '{director}', 6, 33);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — When Do I Do It (Schedule)',
 'The Director''s rhythm is Daily. The standard: Your schedule is the heartbeat of this facility. When you are consistent, the building is consistent. Daily: 6:45 AM — arrive before first staff, building walk, safety check. 7:00 AM — opening procedures, confirm ratios, sign-ins, classrooms ready. 7:00-9:00 AM — morning drop-off window, visible and greeting families. 9:00-11:00 AM — classroom walkthroughs, observe teachers, check lesson plan execution, document. 11:00 AM-12:00 PM — administrative block for documentation, emails, compliance. 12:00-1:00 PM — lunch coverage and supervision check. 1:00-3:00 PM — nap/rest block for staff check-ins and coaching. 3:00-5:30 PM — afternoon pickup window, family communication, incident follow-up. 5:30 PM — closing procedures, ratios confirmed, classrooms closed, building secured. Weekly: Monday — week kickoff, communicate priorities, confirm lesson plans. Tuesday — Director check-in with Operator, review compliance items. Wednesday — mid-week observation focus day. Thursday — staff pulse check, confirm next week''s staffing. Friday — end-of-week debrief, submit weekly report to Operator. Monthly: Full staff meeting, individual lead teacher check-ins, enrollment/retention review with Operator, TRS documentation audit.',
 '{director, schedule, daily, weekly, monthly, rhythm, walkthrough, opening, closing}', 'when-do-i-do-it', '{director}', 3, 34);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — What Do We Talk About',
 'The Director is the communication hub — everything flows through the Director. Communication to Operator (up): Weekly KPI summary covering enrollment, incidents, compliance every Tuesday (no surprises — the Operator should never hear about a problem from someone else), staff performance issues immediately, budget or resource needs directly, operational risks or compliance gaps immediately, team wins and milestones proactively. Communication to Staff (down): Daily priorities and classroom expectations every morning, observation feedback same day (specific and direct), policy or procedure updates in writing then verbally, performance conversations privately and documented, recognition publicly, scheduling changes with maximum notice. Communication to Families (out): Incident escalations and resolutions (Director calls, not teachers), enrollment decisions and waitlist updates, policy changes with written notice, complaints acknowledged within 24 hours and resolved within 72, TRS certification and quality standards confidently. Never: Discuss another staff member''s performance or salary with other staff, make verbal promises not backed by policy, handle serious complaints without documenting, discuss child concerns in common areas, skip escalating safety or compliance issues to the Operator.',
 '{director, communication, channels, operator, staff, families, escalation}', 'what-do-we-talk-about', '{director}', 5, 35);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — Where Do We Go (Escalation Guide)',
 'The Director''s escalation guide. Golden rule: If it could end up in a licensing report, an incident form, or a family complaint — the Operator (Roman) needs to know. Don''t make that call alone. Safety & Emergencies: Child injured or medical emergency — 911 first, Roman second, document everything, notify parent (immediate). Staff acted unsafely with a child — remove from classroom immediately, do not investigate alone, mandatory reporting may apply (immediate, contact Operator + DFPS). Child missing or unaccounted for — lockdown, call 911, call Roman, do not wait (immediate). Compliance & TRS: TRS compliance gap — flag to Roman and reach out to TRS coordinator (same day). Licensing inspector arrives — notify Roman immediately, be professional (immediate). Staff training hours falling behind — bring to Tuesday check-in with a plan (routine). Staff Management: Teacher struggling after two conversations — third instance requires Roman''s awareness (same day). Need to fill classroom urgently — call Hiring Manager directly (same day). Staff complaint about another staff member — loop in Roman (same day). Family Escalations: Family threatening legal action — Roman handles legal exposure, stop responding directly (immediate). Unauthorized pickup attempt — do not release child, call 911 if necessary, notify Roman (immediate). Family still unsatisfied after Director addressed concern — Roman may want to make personal call (same day).',
 '{director, escalation, safety, emergencies, compliance, staff, families, 911}', 'where-do-we-go', '{director}', 5, 36);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'director', 'Director — Why Is It Important',
 'The Director''s role matters because someone has to hold the standard when no one is watching. The Director is the reason NexGen either rises or falls on any given day — the connection between what NexGen promises and what NexGen delivers. Parents trust that the person running the building knows what they are doing, that teachers have been trained, classrooms are supervised, ratios are correct, and the environment is safe. That trust is entirely dependent on the Director enforcing it every single day. The moment standards slip at the Director''s level, they collapse at every level below. Key stats: TRS compliance ultimately rests on the Director''s oversight, parent trust is built or broken by consistency, and staff culture is set by what the Director tolerates.',
 '{director, importance, motivation, purpose, culture, standards}', 'why-is-it-important', '{director}', 8, 37);

-- ─── TEACHER — ALL PAGES ────────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — What Do I Do',
 'Teachers are the core of NexGen. The classroom is the teacher''s domain. Teachers are responsible for the safety, development, and daily experience of every child in their care. Everything else at NexGen exists to support teachers doing this job with excellence. Age groups served: Infant (6 wks-12 mo, focus: safety, sensory stimulation, responsive caregiving, attachment), Older Infant (12-18 mo, focus: mobility support, language emergence, safe exploration), Young Toddler (18-24 mo, focus: parallel play, vocabulary building, routine consistency), Toddler (2-3 yrs, focus: emotional regulation, cooperative play, basic self-help skills), Pre-Kinder (3-4 yrs, focus: school readiness, letter/number foundations, social skills), Kinder (4-5 yrs, focus: literacy, numeracy, independence, group collaboration), Afterschool (5+ yrs, focus: homework support, enrichment, self-defense, social development). Responsibilities: Maintain a safe, clean, engaging environment. Follow the daily schedule consistently. Implement the approved lesson plan weekly. Use positive language and positive behavior guidance (never threats). Document daily observations, incidents, and developmental milestones. Communicate with families at drop-off and pick-up with warmth and professionalism. Participate in self-defense curriculum integration. Complete required training hours. Immediately report any safety concern, injury, or unusual behavior. The standard: Your classroom should run the same whether the Director is watching or not.',
 '{teacher, responsibilities, classroom, safety, ages, curriculum, positive-language}', 'what-do-i-do', '{teacher}', 1, 40);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — How Do I Do It',
 'The Teacher''s procedures: (1) Classroom Setup & Morning Routine — preparing the room before children arrive each day. (2) Lesson Plan Execution — implementing the weekly lesson plan with fidelity and flexibility. (3) Positive Behavior Guidance — language, techniques, and de-escalation strategies for every age group. (4) Incident & Observation Documentation — how and when to document injuries, behaviors, and developmental milestones. (5) Family Communication — drop-off and pick-up protocols, daily reports, and parent conversations. (6) Transition Management — moving children smoothly between activities, meals, and outdoor time. (7) Self-Defense Curriculum Integration — weaving self-defense lessons into the daily schedule.',
 '{teacher, procedures, classroom, lesson-plan, behavior, documentation, families, transitions}', 'how-do-i-do-it', '{teacher}', 4, 41);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — How Do I Know (Performance Scoring)',
 'The Teacher is measured by what happens inside the classroom every day. Performance categories: (1) TRS Classroom Assessment (30%) — environment meets TRS criteria (green: fully compliant), positive language used consistently (green: always observed), daily schedule posted and followed (green: yes, consistently). (2) Lesson Plan Execution (25%) — plan submitted by Thursday (green: every week), plan implemented as written (green: fully executed), all developmental domains covered weekly (green: all 4 domains). (3) Internal Observations (20%) — children engaged and on-task (green: consistently), teacher-child interactions warm and responsive (green: always), ratios and supervision maintained (green: always). (4) Parent Feedback (15%) — parent review score (green: 4.5+ avg), daily communication at pickup (green: consistent and specific). (5) Daily Self Check-In (10%) — submitted daily (green: every day), responses specific and honest (green: detailed and actionable).',
 '{teacher, performance, scoring, trs, lesson-plan, observations, parents, checkin}', 'how-do-i-know', '{teacher}', 6, 42);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — Important Metrics',
 'The Teacher measures what happens inside the classroom every single day. North star: Is every child in my classroom safe, engaged, and developing on track? Cadence: Daily self-check, weekly lesson plan review, monthly developmental documentation. Classroom Quality: TRS Observation Score from Director (target 8+ out of 10), Positive Language Rate (target no negative framing), Daily Schedule Adherence (target consistent). Curriculum: Lesson Plan On-Time Submission (target every Thursday), Lesson Plan Implementation Rate (target fully executed), Developmental Domains Covered (target all 4 weekly). Documentation: Daily Check-In Completion (target every day), Incident Reports Same-Day (target 100%), Monthly Developmental Observations (target all children documented).',
 '{teacher, metrics, kpis, classroom, curriculum, documentation, trs}', 'important-metrics', '{teacher}', 6, 43);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — When Do I Do It (Schedule)',
 'The Teacher''s rhythm is Daily. The standard: Your classroom runs on routine. The children know what to do because you do it the same way every day. Consistency is not rigidity — it is safety. Daily: 7:00 AM — classroom setup, materials ready before children arrive. 7:00-9:00 AM — morning arrival, greet each child by name, connect with parents. 9:00-9:30 AM — morning meeting/circle time with calendar, weather, daily theme. 9:30-11:00 AM — structured learning block with lesson plan activities, small groups, centers. 11:00-11:30 AM — handwashing, transition to lunch. 11:30 AM-12:15 PM — lunch, seat children, assist, model conversation. 12:15-2:15 PM — rest/nap time, supervise, document observations, prep afternoon. 2:15-3:00 PM — afternoon activity with movement, outdoor time, enrichment. 3:00-3:30 PM — snack. 3:30-5:30 PM — afternoon centers, pickup window, communicate with families. 5:30 PM — classroom close-down, clean, restock, complete daily documentation. Weekly: Thursday — submit next week''s lesson plan. Friday — reflect on the week. Monthly: Developmental observation documentation for each child, attend full staff meeting, review updated classroom standards.',
 '{teacher, schedule, daily, weekly, monthly, rhythm, classroom, routine}', 'when-do-i-do-it', '{teacher}', 3, 44);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher', 'Teacher — Communication + Escalation + Why',
 'Communication: The Teacher talks about children — progress, needs, and their day. To Director (up): developmental/behavioral concerns as soon as a pattern is noticed, classroom resource needs proactively, parent tension before it becomes a complaint, safety concerns immediately, lesson plan questions through Lesson Plans Manager first, staffing coverage needs with maximum notice. To Families (out): daily highlights at pickup with specifics, positive behavioral moments, minor concerns casually, upcoming themes when asked. To Assistant (down): the day''s plan before children arrive, which children need extra attention, feedback on support, specific needs during activities. Never: share a child''s information except with Director or parent, discuss another family, make enrollment/policy commitments, handle formal complaints alone, use negative language. Escalation golden rule: If a child is in danger — act first, ask questions second. For everything else, the Director is the resource. Child seriously injured — 911 + Director (immediate). Suspected abuse — Director immediately, mandatory reporting. Medical episode — emergency protocol, call 911. Can''t execute lesson plan — contact Lesson Plans Manager same day. Parent upset — acknowledge and bring Director in. Why it matters: 90% of brain development occurs before age 5. Every interaction is either building something or breaking something — there is no neutral. Teachers may be the most consistent, caring adult in some of these children''s lives.',
 '{teacher, communication, escalation, importance, children, families, safety}', 'what-do-we-talk-about', '{teacher}', 5, 45);

-- ─── TEACHER ASSISTANT — ALL PAGES ──────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher-assistant', 'Teacher Assistant — What Do I Do',
 'Teacher Assistants support lead teachers in delivering a safe, structured, and nurturing classroom experience. The assistant is not a substitute — the assistant is a partner. Attentiveness, consistency, and willingness to learn directly impacts the quality of every child''s day. Responsibilities: Support the lead teacher in all classroom activities and transitions. Maintain active supervision of all children at all times. Help set up and clean up materials for lessons and activities. Assist with diapering, feeding, and personal care routines. Use the same positive language and behavior guidance as the lead teacher. Step up to lead the classroom if the teacher steps out — no gaps in coverage. Document any incidents, injuries, or concerns immediately. Follow the classroom schedule without needing to be reminded. Ask questions and seek to grow into a lead teacher role. The standard: Be so reliable that the lead teacher never has to wonder if you have got it.',
 '{teacher-assistant, responsibilities, support, supervision, classroom}', 'what-do-i-do', '{teacher-assistant}', 1, 50);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher-assistant', 'Teacher Assistant — How Do I Do It + Performance Scoring',
 'Procedures: (1) Active Supervision Protocols — positioning, scanning, and engagement techniques during all activities. (2) Classroom Support Routines — setup, cleanup, and material prep throughout the day. (3) Stepping Up as Lead — what to do when the lead teacher steps out. (4) Personal Care Procedures — diapering, feeding, hygiene with proper documentation. (5) Incident Reporting — documenting and reporting concerns in real time. Performance scoring: (1) Active Supervision (35%) — eyes on room at all times (green: always, red: phone use or checked out), positioned to see all children (green: consistently correct). (2) Activity Support (25%) — materials prepped without being asked (green: proactive), transitions managed smoothly (green: leads confidently). (3) Internal Observations (25%) — uses positive language (green: consistently), supports lead without conflict (green: seamless partnership). (4) Daily Self Check-In (15%) — submitted daily.',
 '{teacher-assistant, procedures, performance, supervision, support, observations}', 'how-do-i-do-it', '{teacher-assistant}', 4, 51);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'teacher-assistant', 'Teacher Assistant — Metrics + Schedule + Communication + Escalation + Why',
 'Metrics: North star: Is every child supervised and supported at all times? Evaluated through daily Director observations and weekly lead teacher check-in. Active Supervision Score (target no lapses), Room Positioning (target always correct), On-Time Attendance (target every shift), Daily Check-In (target every day), Materials Prepped (target proactive), Director Observation Score (target 7+/10). Schedule: Daily rhythm — 7:00 AM arrive and support setup, 7:00-9:00 AM morning arrival support, 9:00 AM-12:00 PM morning learning block support, 12:00-12:15 PM lunch prep, 12:15-2:15 PM rest time supervision, 2:15-5:30 PM afternoon support, 5:30 PM close-down. Monthly: staff meeting, training hours. Communication: To Lead Teacher (up): anything concerning observed immediately, communicate before stepping away, ask questions instead of guessing, flag supply needs early. To Families (out): warm greetings, basic positive updates, redirect all policy/billing/incident questions. Never: share child information broadly, discuss other families, speculate on incidents. Escalation: Lead teacher is first resource always. Only skip if child safety is at immediate risk and lead is absent. Child hurt and lead not present — secure child, get Director (immediate). Something feels wrong — tell lead teacher immediately. Why it matters: A teacher without backup is a classroom at risk. The assistant is not a backup plan — the assistant is half of the equation. One lapse in supervision is all it takes.',
 '{teacher-assistant, metrics, schedule, communication, escalation, importance}', 'important-metrics', '{teacher-assistant}', 3, 52);

-- ─── FRONT DESK MANAGER — ALL PAGES ────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'front-desk', 'Front Desk Manager — What Do I Do',
 'The Front Desk Manager owns the family-facing experience from the moment someone walks through the door. The Front Desk manages daily check-ins, communication, inquiries, and the general pulse of the front of house. The Front Desk is the operational nerve center of NexGen''s day. Responsibilities: Greet every family and child by name — warmth is non-negotiable. Manage daily check-in and check-out using the attendance system. Answer all inbound calls, texts, and emails promptly and professionally. Direct tour inquiries to the Tour Manager and log all leads. Communicate daily updates, closures, and announcements to families. Monitor and manage the lobby, entrance, and front-of-house environment. Handle billing questions and escalate to the Director when needed. Track and log visitor sign-ins for compliance. Support the Director with administrative tasks. The standard: Families form their opinion of NexGen in the first 30 seconds. Make it count every time.',
 '{front-desk, responsibilities, families, check-in, communication, lobby}', 'what-do-i-do', '{front-desk}', 1, 60);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'front-desk', 'Front Desk Manager — How + Performance + Metrics + Schedule + Escalation + Why',
 'Procedures: (1) Morning Open — unlocking, system checks, greeting protocol. (2) Check-In & Check-Out — step-by-step attendance tracking. (3) Phone & Email Response Standards — response times, tone, escalation. (4) Visitor & Tour Intake — logging visitors, directing inquiries. (5) End-of-Day Close — system shutdown, daily reporting, handoff notes. Performance: Family Experience (35%) — greeted by name (target 100%), parent satisfaction (target 4.5+), complaint escalation same day. Attendance & Records (30%) — check-in real-time, visitor log complete. Inquiry Response Time (20%) — answered within 3 rings, tour inquiries logged same day. Check-In (15%). Schedule: 6:45 AM arrive. 7:00-9:00 AM check-in window. 9:00-11:00 AM calls, emails, scheduling. 11:00-1:00 PM admin/billing. 1:00-3:00 PM follow-ups, CRM. 3:00-5:30 PM pickup window. 5:30 PM close. Weekly: Monday newsletter, Friday tour schedule review. Monthly: audit contacts, staff meeting. Escalation: The moment a situation feels above your authority, it is — escalate early. Unauthorized pickup — do not release child, get Director immediately (immediate). Aggressive person at door — get Director, call 911 if threat (immediate). Billing dispute — get Director same day. Parent asking about incident — acknowledge and get Director. Why it matters: Trust is built in the first 30 seconds. Enrollment revenue keeps the school open — the front desk is the first reason families stay or go.',
 '{front-desk, procedures, performance, metrics, schedule, escalation, importance}', 'how-do-i-do-it', '{front-desk}', 3, 61);

-- ─── HIRING MANAGER — ALL PAGES ─────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'hiring-manager', 'Hiring Manager — What Do I Do',
 'The Hiring Manager owns the full recruitment lifecycle at NexGen — from job posting to first-day onboarding handoff. The Hiring Manager is responsible for finding the right people, filtering out the wrong ones, and ensuring no classroom is ever left understaffed. Responsibilities: Post and manage job listings across all relevant platforms. Screen applicants for alignment with NexGen''s values and minimum qualifications. Conduct first-round interviews and advance candidates to the Director. Coordinate background checks, reference calls, and required documentation. Maintain an active candidate pipeline — always recruiting, not just when urgent. Track open positions and communicate hiring status to the Director and Operator. Support new hire onboarding paperwork and first-day logistics. Flag retention risks and communicate patterns to leadership. The standard: A bad hire costs more than a slow hire. Your filter is one of the most important systems in the building.',
 '{hiring-manager, responsibilities, recruitment, pipeline, screening, onboarding}', 'what-do-i-do', '{hiring-manager}', 1, 70);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'hiring-manager', 'Hiring Manager — How + Performance + Metrics + Schedule + Escalation + Why',
 'Procedures: (1) Job Posting & Platform Management. (2) Applicant Screening Process — resume criteria, phone screen questions, advancement rules. (3) Interview Workflow — first-round structure, scoring rubric, handoff to Director. (4) Background Check & Documentation — required checks, timelines, compliance. (5) Pipeline Management — maintaining bench candidates, tracking positions. Performance: Hire Quality (40%) — 90-day retention (green: 85%+), new hire performance (green: meeting expectations). Time to Fill (25%) — average (green: under 14 days), pipeline maintained proactively. Onboarding Compliance (20%) — background checks pre-start (green: 100%), docs complete day one. Metrics: Active Candidates (target 3+ per open role), Time to Fill (target under 14 days), Postings Current (target always live), 90-Day Retention (target 85%+), Background Checks (target 100%). Schedule: Monday — review applications, refresh listings. Tuesday — interviews, update Operator. Wednesday — reference/background checks. Thursday — offer letters/rejections. Friday — weekly report, plan outreach. Monthly: audit positions, review time-to-hire, refresh strategy, staff meeting. Communication: To Director — candidate status updates, concerns, red flags, open positions, hiring timelines. To Operator — pipeline health, retention patterns, staffing forecasts. Never: advance a candidate who doesn''t meet minimum qualifications, start a new hire without background check complete, make promises about start dates without Director alignment. Why it matters: Who we hire determines who our children are cared for by. One wrong hire is a safety risk. One great hire elevates an entire team. The gatekeeper of who enters the lives of children in NexGen''s care.',
 '{hiring-manager, procedures, performance, metrics, schedule, communication, escalation, importance}', 'how-do-i-do-it', '{hiring-manager}', 3, 71);

-- ─── TOUR MANAGER — ALL PAGES ───────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'tour-manager', 'Tour Manager — What Do I Do',
 'The Tour Manager owns the enrollment conversion experience. When a family walks in for a tour, the Tour Manager is responsible for making them feel seen, informed, and confident enough to say yes. This is a sales and relationship role — not a show-and-tell. Responsibilities: Schedule and confirm all tour appointments promptly. Lead every tour with a structured, warm, and informative script. Highlight NexGen''s differentiators — TRS, self-defense, culture, curriculum. Follow up with all tour families within 24 hours via phone or text. Track tour-to-enrollment conversion and report weekly. Identify objections and address them confidently without pressure. Coordinate with Front Desk for smooth tour day logistics. Log all tour activity and family notes into the enrollment CRM. The standard: Families are not just buying childcare. They are trusting you with their child. Sell with that in mind.',
 '{tour-manager, responsibilities, tours, enrollment, conversion, families}', 'what-do-i-do', '{tour-manager}', 1, 80);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'tour-manager', 'Tour Manager — How + Performance + Metrics + Schedule + Escalation + Why',
 'Procedures: (1) Tour Scheduling & Confirmation — booking, reminders, no-show follow-up. (2) Tour Script & Walkthrough — structured flow. (3) Objection Handling Guide. (4) Follow-Up Sequence — 24-hour, 3-day, 7-day. (5) Conversion Tracking — logging, rates, weekly reporting. Performance: Conversion (40%) — rate (green: 40%+), follow-up within 24 hrs (green: 100%). Volume (25%) — per week (green: 6+), no-show rate (green: under 15%). Experience Quality (20%) — structured route (green: consistently). CRM Accuracy (15%) — notes same day. Metrics: Conversion Rate (target 40%+), Follow-Up (target 100% within 24 hrs), Tours/Week (target 6+), No-Show Rate (target under 15%), CRM Notes (target same day). Schedule: Daily — confirm tours, prep 30 min before, structured walkthrough, log notes within 2 hours, follow up same day. Weekly: Monday — review tours and follow-ups. Friday — submit report, flag close-to-decision families. Monthly: review conversion rate with Director, identify objections, staff meeting. Communication: To Director — weekly tour reports, families in pipeline, conversion metrics. To Front Desk — tour schedules, lobby readiness needs. Never: make promises about availability or pricing without checking, give tours without preparation, skip follow-up. Why it matters: Every empty spot is a family that has not found NexGen yet. Conversion is not a sales metric — it is the mechanism by which children access quality care.',
 '{tour-manager, procedures, performance, metrics, schedule, communication, escalation, importance}', 'how-do-i-do-it', '{tour-manager}', 3, 81);

-- ─── LESSON PLANS MANAGER — ALL PAGES ──────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'lesson-plans', 'Lesson Plans Manager — What Do I Do',
 'The Lesson Plans Manager is responsible for building, distributing, and reviewing the weekly curriculum for every age group at NexGen. The Lesson Plans Manager ensures that every classroom has a structured, developmentally appropriate, and TRS-aligned plan ready before the week begins. Responsibilities: Build weekly lesson plans for all age groups from Infant through Afterschool. Ensure all plans are developmentally appropriate and TRS compliant. Distribute finalized plans to each lead teacher by Thursday for the following week. Review submitted lesson plans from teachers and provide feedback. Maintain a library of activities, themes, and learning objectives by age group. Coordinate with the Director on seasonal themes, events, and special programming. Track and document lesson plan completion and implementation quality. Support teachers who need help adapting plans for their specific group. The standard: A week without a plan is a week of improvisation. Your consistency gives teachers confidence.',
 '{lesson-plans, responsibilities, curriculum, trs, age-groups, distribution}', 'what-do-i-do', '{lesson-plans}', 1, 90);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'lesson-plans', 'Lesson Plans Manager — How + Performance + Metrics + Schedule + Why',
 'Procedures: (1) Weekly Planning Process — timeline, inputs, approval workflow. (2) Age-Appropriate Activity Design — frameworks for each developmental stage. (3) TRS Alignment Checklist — verifying plans meet TRS requirements. (4) Teacher Feedback Loop — collecting and incorporating classroom feedback. (5) Activity Library Management — organizing activities and themes. Performance: Delivery — plans by Thursday (green: all rooms every week), receipt confirmed. Quality — all 4 domains covered (green: always), TRS aligned (green: fully), teacher-rated usability (green: useful). Implementation — mid-week check (green: every week), non-implementation flags to Director. Metrics: Plans By Thursday (target 100%), Receipt Confirmed (target weekly), 4 Domains (target every plan), TRS Alignment (target fully aligned), Mid-Week Check (target weekly). Schedule: Monday — review themes, begin drafting. Tuesday — infant through toddler plans. Wednesday — Pre-K through afterschool, TRS review. Thursday — finalize and distribute all plans (hard deadline). Friday — follow up, gather materials for next cycle. Monthly: themes for next month, audit with Director, staff meeting, update library. Communication: To Teachers — distribute plans, provide guidance, address questions. To Director — plan completion status, implementation quality, TRS alignment. Never: deliver plans late, skip any age group, ignore teacher feedback. Why it matters: A classroom without a plan is a classroom without direction. Every unplanned day is a developmental opportunity a child will never get back.',
 '{lesson-plans, procedures, performance, metrics, schedule, communication, importance}', 'how-do-i-do-it', '{lesson-plans}', 3, 91);

-- ─── KITCHEN MANAGER — ALL PAGES ────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'kitchen-manager', 'Kitchen Manager — What Do I Do',
 'The Kitchen Manager is responsible for all food service operations at NexGen — from planning and purchasing to preparation, serving, and cleanup. The Kitchen Manager maintains full compliance with CACFP and state food service requirements while delivering nutritious, child-friendly meals every day. Responsibilities: Plan and prepare breakfast, lunch, and snacks for all enrolled children daily. Ensure all meals meet CACFP nutritional requirements and portion standards. Manage food inventory, ordering, and vendor relationships. Maintain kitchen cleanliness and food safety standards at all times. Post and follow the approved menu — no substitutions without Director approval. Track and document all food service records for compliance audits. Accommodate documented dietary restrictions and allergies without error. Coordinate meal timing with classroom schedules. Train and supervise the Assistant Kitchen Manager. The standard: A hungry child can''t learn. A sick child can''t attend. Your standards protect both.',
 '{kitchen-manager, responsibilities, food-service, cacfp, meals, safety, allergies}', 'what-do-i-do', '{kitchen-manager}', 1, 100);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'kitchen-manager', 'Kitchen Manager — How + Performance + Metrics + Schedule + Escalation + Why',
 'Procedures: (1) Daily Meal Prep Routine. (2) CACFP Compliance Documentation. (3) Inventory & Ordering Process. (4) Allergy & Dietary Accommodation — zero-error protocols. (5) Kitchen Safety & Sanitation — daily/weekly/monthly checklists. Performance: Food Safety — daily temp logs (green: every day), violations (green: zero), allergy errors (green: zero). CACFP Compliance — meal records daily (green: every day), monthly submission (green: on time). Service — meals on schedule. Metrics: Temp Logs (target daily), Violations (target zero), Allergy Errors (target zero), CACFP Records (target 100%), Monthly Submission (target always on time). Schedule: 6:45 AM — kitchen open, temp checks, breakfast prep. 7:30-8:30 AM — breakfast service. 8:30-9:30 AM — cleanup, lunch prep begins. 9:30-11:00 AM — full lunch prep. 11:30 AM-12:30 PM — lunch service. 12:30-1:30 PM — cleanup, CACFP documentation. 1:30-2:30 PM — snack prep. 3:00-3:30 PM — snack service. 3:30-4:30 PM — final cleanup, inventory, next-day notes. Weekly: Monday — post menu, confirm inventory. Friday — inventory audit, submit order. Monthly: equipment inspection, CACFP review, menu planning, staff meeting. Communication: To Director — menu changes, dietary updates, CACFP status, supply needs. To Asst. Kitchen Manager — daily task assignments, standards reinforcement. Never: substitute menu items without Director approval, skip temperature logs, ignore allergy documentation. Escalation: Food safety incident — notify Director immediately. CACFP audit concerns — Director same day. Supply emergency — Director for budget approval. Why it matters: Nutrition at this age is developmental. For many children, NexGen meals may be the most nutritionally complete meal they get all day. One allergy error or food safety lapse has immediate and serious consequences.',
 '{kitchen-manager, procedures, performance, metrics, schedule, communication, escalation, importance}', 'how-do-i-do-it', '{kitchen-manager}', 3, 101);

-- ─── ASST. KITCHEN MANAGER — ALL PAGES ─────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'asst-kitchen', 'Asst. Kitchen Manager — Complete Role Guide',
 'The Assistant Kitchen Manager supports the Kitchen Manager in all food preparation, service, and compliance duties. The assistant is trained to step in fully when needed and holds the same standards as the lead at all times. Responsibilities: Assist with all meal preparation and serving under the Kitchen Manager''s direction. Maintain kitchen cleanliness and sanitation throughout the day. Support inventory tracking and flag low stock. Follow all food safety and CACFP protocols without exception. Step in as acting Kitchen Manager during absences — same standards apply. Help document meals served and allergy/portion adjustments. Complete required food handler certifications. Procedures: (1) Meal Prep Support — prep, plating, serving. (2) Sanitation Routines — ongoing cleaning, end-of-day deep clean. (3) Stepping In as Lead — full Kitchen Manager duties during absences. (4) Inventory Flagging — tracking stock, alerting Kitchen Manager. Schedule mirrors Kitchen Manager: 6:45 AM arrival, breakfast support (7:30-8:30), cleanup and lunch prep (8:30-11:00), lunch service (11:30-12:30), cleanup and snack prep (12:30-2:30), snack service and final cleanup (3:00-4:30). Monthly: staff meeting, food handler certification renewals. Communication: To Kitchen Manager — stock levels, equipment issues, task questions. Never: deviate from approved menu, skip CACFP protocols, ignore allergy documentation. The standard: When the Kitchen Manager is not here, nothing changes. Why it matters: The kitchen cannot stop even when the lead is not there. Treating the role as secondary makes the kitchen fragile. Treating it as equally important makes the kitchen unbreakable.',
 '{asst-kitchen, responsibilities, procedures, schedule, food-service, cacfp, backup, importance}', 'what-do-i-do', '{asst-kitchen}', 2, 110);

-- ─── BUS DRIVER — ALL PAGES ─────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('role', 'bus-driver', 'Bus Driver — Complete Role Guide',
 'Bus Drivers are responsible for the safe, timely, and organized transportation of children to and from NexGen. The vehicle is an extension of the classroom — the same standards apply. Responsibilities: Full pre-trip inspection before every run, every child properly secured before moving, follow approved routes, current headcount at every stop, communicate delays/incidents to Director immediately, clean and safe vehicle, no phone while vehicle in motion, complete transportation logs daily, hold current CDL, CPR, and state certifications. Procedures: (1) Pre-Trip Vehicle Inspection — no exceptions. (2) Pickup & Drop-Off — stop protocol, child verification, parent handoff. (3) Headcount Protocol — every stop, before every move. (4) Incident & Delay Communication — immediate to Director. (5) Vehicle Maintenance & Logs — daily logs, mileage, requests. Schedule: 45 min before first pickup — pre-trip inspection. Morning route — pickups with headcount at every door. Upon NexGen arrival — final headcount, hand off to staff. Mid-day transport — same standards. Afternoon — afterschool pickups, secured dropoffs. After last drop — post-trip inspection, sweep vehicle, complete log. Weekly: Monday — review route manifest. Friday — submit logs, report maintenance. Monthly: full vehicle inspection, CDL check, staff meeting, review emergency procedures. Communication: To Director — delays, incidents, route changes (immediately), vehicle maintenance needs, certification status. To Families — arrival time updates, warm handoffs. Never: use phone while driving, leave child unaccounted, deviate from routes without authorization. Why it matters: Zero margin for error in child transportation. A parent''s worst fear lives in the Bus Driver''s hands every route. There is no partial credit — every lapse has consequences that cannot be undone.',
 '{bus-driver, responsibilities, procedures, schedule, transportation, safety, headcount, cdl, importance}', 'what-do-i-do', '{bus-driver}', 2, 120);

-- ─── MEETING SCHEDULES ──────────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Daily Huddle',
 'The Daily Huddle is a 10-15 minute meeting held every morning (first thing). Owner: Founder. Attendees: Founder, Operator, Director. Purpose: Quick alignment — not a strategy session, a pulse check. The only question: Does today break anywhere? Agenda: (1) Today''s staffing and ratios — any gaps? (2) Tours scheduled for today — is Tour Manager prepped? (3) Any fires — parent issues, staff issues, anything urgent. Keep it tight, 15 minutes max. If something needs a deeper conversation, schedule it separately.',
 '{meeting, daily-huddle, daily, staffing, tours, alignment}', 'when-do-we-meet', '{founder, operator, director}', 3, 130);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Weekly Leadership Memos',
 'The Weekly Leadership Memos is a 45-60 minute meeting held every Tuesday after the Operator-Director check-in. Owner: Founder. Attendees: Founder, Operator, Director. Purpose: The strategic operating meeting for the leadership team. Review all KPIs, identify what is red, set priorities, and assign ownership with deadlines. Agenda: (1) Scorecard Review (10-15 min) — look at all KPIs, circle anything red. (2) Wins/Losses (5 min) — 1-2 big wins, 1-2 issues. (3) Top 3 Priorities (15-20 min) — what to fix next week. (4) Who/What/When (15 min) — assign owners and due dates. Founder runs the agenda. Operator and Director come prepared with their numbers.',
 '{meeting, weekly-leadership, tuesday, kpis, priorities, strategy}', 'when-do-we-meet', '{founder, operator, director}', 3, 131);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Monthly Finance Review',
 'The Monthly Finance Review is a 60-90 minute meeting held by the 20th of each month. Owner: Founder. Attendees: Founder, Operator. Purpose: Review the financial health of NexGen. Agenda: (1) Review last 3 months P&L — revenue trend up, flat, or down? (2) Check 3 key ratios: Payroll % of Revenue (target 50-55%), Average Revenue per Child, Net Profit % (target 20%+). (3) Ask 3 diagnostic questions: fill more seats? raise prices? control a cost bucket? (4) Pick ONE finance decision — pricing change, expense cut, or enrollment push. No meeting ends without a specific finance decision. Founder leads, Robyn brings operational context, bookkeeper optionally on Zoom.',
 '{meeting, monthly-finance, finance, ratios, decisions}', 'when-do-we-meet', '{founder, operator}', 3, 132);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Operator-Director Weekly Check-In',
 'The Operator-Director Check-In is a 45-minute meeting held every Tuesday at 9:00 AM. Owner: Operator. Attendees: Founder, Operator, Director. Purpose: The most important meeting in the building. Roman and the Director align on weekly priorities, surface issues, review KPIs, and make operational decisions. Agenda: (1) KPIs from last week — enrollment, incidents, compliance flags. (2) What is working / what broke down. (3) Staffing gaps or performance issues. (4) Upcoming compliance deadlines or TRS items. (5) Priorities for the coming week. (6) Anything the Director needs from the Operator. Roman runs the agenda. Director comes prepared with updates.',
 '{meeting, operator-director, tuesday, kpis, priorities, alignment}', 'when-do-we-meet', '{founder, operator, director}', 3, 133);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Full Staff Meeting',
 'The Full Staff Meeting is a 60-minute meeting held the first Monday of each month at 6:30 PM. Owner: Director. Attendees: All staff (every NexGen team member). Purpose: Culture, alignment, and recognition — not a gripe session, a momentum builder. Director runs it, Roman attends and closes. Agenda: (1) Recognition — specific wins from the past month. (2) School-wide updates — enrollment, programs, TRS progress. (3) Policy or procedure changes. (4) Training or development spotlight. (5) Open floor — questions and concerns (time-boxed to 10 min). (6) Roman''s close — vision, direction, what we are building toward. Director prepares agenda by the Friday before.',
 '{meeting, full-staff, monthly, culture, recognition, all-staff}', 'when-do-we-meet', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 3, 134);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Director-Teacher Check-In + Observation Debrief',
 'Director-Lead Teacher Check-In: 20-minute per teacher meeting held bi-weekly on Wednesdays during nap time (1:00 PM). Owner: Director. One-on-one support conversation. Agenda: How is your classroom feeling? Children you are concerned about? Lesson plan feedback? Parent communication wins/tensions? What do you need from me? Observation Debrief: 10-15 minute meeting held weekly, same day as observation. Owner: Director. Attendees: Director + Teacher (+ Assistant). Brief real-time feedback loop. Agenda: One specific thing done well, one thing to adjust with clear direction, any immediate safety or compliance concern. Keep under 15 minutes — specific feedback only.',
 '{meeting, director-teacher, biweekly, observation, debrief, feedback}', 'when-do-we-meet', '{director, teacher, teacher-assistant}', 3, 135);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'meetings', 'NexGen — Other Recurring Meetings',
 'Additional meetings: (1) Lesson Plan Review — weekly Thursday by 3:00 PM, async. Owner: Lesson Plans Manager. Plans distributed, teachers confirm receipt, questions addressed same day. If teacher has not confirmed by 4 PM, Lesson Plans Manager follows up directly. (2) Hiring Pipeline Review — weekly Tuesday, 15 min, after Operator-Director check-in. Owner: Hiring Manager. Status on open positions, active candidates, urgent fills. (3) Weekly Tour Debrief — Friday 4:00 PM, 20 min. Owner: Tour Manager. Tour activity, conversions, objections, undecided families. Tour Manager comes with CRM data. (4) Monthly Menu Planning — last Friday of month, 30 min. Owner: Kitchen Manager. Next month''s menu, dietary changes, CACFP notes, supply concerns. Director must approve menu before posting. (5) Route and Safety Review — monthly first Monday 5:30 PM, 20 min before Full Staff. Owner: Director. Transport logs, vehicle maintenance, CDL status, route changes. (6) Quarterly Business Review — first week of quarter, 90 min. Owner: Operator. Enrollment vs. target, financial review, TRS/compliance status, staff performance, top 3 wins, top 3 failures, next quarter priorities (3 max).',
 '{meeting, lesson-plan-review, hiring, tours, menu, route, quarterly}', 'when-do-we-meet', '{director, teacher, hiring-manager, tour-manager, lesson-plans, kitchen-manager, bus-driver, operator}', 5, 136);

-- ─── COMMUNICATION FRAMEWORK + ESCALATION CONTACTS ──────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'communication', 'NexGen — Communication and Meeting Framework',
 'NexGen uses a structured communication and meeting agenda framework centered on four questions: (1) Where Are We — current status, numbers, and observations. (2) Where Are We Going — goals, targets, and priorities. (3) Why Are We Going There — the purpose and impact behind the targets. (4) Scorecard Review — reviewing KPIs, circling anything red, and assigning action items. Slack is the central communication platform — if it is not in Slack it did not happen. The NexGen Operating System (the Compass software) is the single source of truth for role clarity, procedures, KPIs, escalation paths, and meeting cadences. Slack is where you communicate, the NexGen OS is where you operate.',
 '{communication, framework, slack, nexgen-os, agenda, scorecard}', 'what-do-we-talk-about', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 5, 140);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('business_context', 'escalation', 'NexGen — Escalation Contacts and Urgency Levels',
 'NexGen uses four urgency levels for escalation: (1) Immediately — emergencies, safety threats, compliance violations. (2) Same Day — urgent issues that cannot wait for the next check-in. (3) Next Check-In / Routine — items for the next scheduled meeting. (4) As Needed / Async — non-urgent items. Key contacts: Founder (Roman), Operator (Roman), Director, Lead Teacher, Lesson Plans Manager, Hiring Manager, Tour Manager, Kitchen Manager, Front Desk Manager. External contacts: DFPS/Licensing (State) for licensing issues, TRS Assessor for certification questions, CACFP Sponsor for food program compliance, 911 for emergencies. General principle: When in doubt, escalate early. It is always better to escalate too early than too late. Chain of command: Teacher Assistant to Lead Teacher to Director to Operator/Founder. Front Desk to Director for complaints and unusual situations. All safety emergencies: 911 first, then Director, then Operator.',
 '{escalation, contacts, urgency, emergency, dfps, trs, cacfp, 911, chain-of-command}', 'where-do-we-go', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 3, 150);

-- ─── QUICK REFERENCE / FAQ ──────────────────────────────────────────────────

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('faq', 'kpis', 'KPI Quick Reference — All Roles',
 'Key KPIs by role: FOUNDER: Occupancy % (85%+), Payroll % of Revenue (50-55%), Average Revenue per Child, Net Profit % (20%+), Cash in Bank (above 1 month expenses), New Enrollments/Withdrawals (net positive). OPERATOR: Monthly Revenue vs Target, Operating Expense Ratio (under 75%), Net Profit Margin (15%+), Enrollment vs Capacity (85%+), Waitlist Length (5+), TRS Status (4-5 Star), Staff Turnover (under 20%). DIRECTOR: TRS Compliance (100% rooms), Staff Attendance (95%+), Parent Satisfaction (4.5+/5), Complaint Resolution (within 24 hrs), Family Retention (85%+), Observations (all rooms weekly). TEACHER: TRS Observation Score (8+/10), Lesson Plan On-Time (every Thursday), All 4 Domains Weekly, Schedule Adherence, Daily Check-In. TEACHER ASSISTANT: Active Supervision (no lapses), Attendance (every shift), Director Observation (7+/10). FRONT DESK: Greeted by Name (100%), Attendance Accuracy (100%), Inquiry Response (within 3 rings), Tour Inquiries Logged. TOUR MANAGER: Conversion Rate (40%+), Tours/Week (6+), Follow-Up (within 24 hrs), No-Show Rate (under 15%). HIRING MANAGER: Time to Fill (under 14 days), 90-Day Retention (85%+), Pipeline (3+ per open role), Background Checks (100%). LESSON PLANS: Plans by Thursday (100%), All 4 Domains, TRS Aligned, Mid-Week Check. KITCHEN: Zero food safety incidents, CACFP compliance, Meals on time, Temp logs daily. BUS DRIVER: Pre-trip inspection every run, Headcount every stop, Zero phone use while driving, Logs submitted weekly.',
 '{kpis, metrics, quick-reference, all-roles}', 'important-metrics', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 1, 160);

INSERT INTO knowledge_base (category, subcategory, title, content, tags, source_page, role_ids, priority, sort_order) VALUES
('faq', 'meetings', 'Meeting Schedule Quick Reference',
 'NexGen meeting schedule: DAILY: Daily Huddle (Founder + Operator + Director, morning, 10-15 min). WEEKLY: Operator-Director Check-In (Tuesday 9 AM, 45 min), Weekly Leadership Memos (Tuesday, 45-60 min), Hiring Pipeline Review (Tuesday, 15 min), Observation Debrief (after observation, 10-15 min), Lesson Plan Review (Thursday by 3 PM, async), Weekly Tour Debrief (Friday 4 PM, 20 min). BI-WEEKLY: Director-Teacher Check-In (Wednesday 1 PM during nap, 20 min per teacher). MONTHLY: Monthly Finance Review (by the 20th, 60-90 min), Full Staff Meeting (First Monday 6:30 PM, 60 min), Monthly Menu Planning (Last Friday 3:30 PM, 30 min), Route and Safety Review (First Monday 5:30 PM, 20 min). QUARTERLY: Quarterly Business Review (first week of quarter, 90 min).',
 '{meetings, schedule, cadence, calendar, quick-reference}', 'when-do-we-meet', '{founder, operator, director, teacher, teacher-assistant, front-desk, hiring-manager, tour-manager, lesson-plans, kitchen-manager, asst-kitchen, bus-driver}', 1, 161);

-- ============================================================================
-- TOTAL: ~55 INSERT statements covering all 10 Compass pages and all 12 roles
-- Every role has coverage from: What Do I Do, How Do I Do It, How Do I Know,
-- Important Metrics, When Do I Do It, What Do We Talk About, Where Do We Go,
-- Why Is It Important
-- Plus: 7 business_context docs, 7 meeting docs, 2 FAQ quick-reference docs
-- ============================================================================
